name: Bug Report
description: Report a bug in AI Usage Bar
labels: ["bug"]
body:
  - type: dropdown
    id: macos-version
    attributes:
      label: macOS Version
      options:
        - macOS 15 Sequoia
        - macOS 14 Sonoma
        - macOS 13 Ventura
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: Found in the menu bar panel or release you downloaded
      placeholder: "e.g. 1.0.0"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Open AI Usage Bar
        2. Click on ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Optional — drag and drop images here
    validations:
      required: false
